services:
  guardian:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: "20.18.0"
    image: guardian-platform:latest
    container_name: guardian-platform
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - SKIP_ENV_VALIDATION=0
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 40s
      retries: 3
    restart: unless-stopped
    networks:
      - guardian-network

  guardian-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: guardian-platform:dev
    container_name: guardian-platform-dev
    ports:
      - "3001:3000"
      - "5555:5555"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.env.local:/app/.env.local
    restart: unless-stopped
    networks:
      - guardian-network
    profiles:
      - dev

networks:
  guardian-network:
    driver: bridge
